[tool.pylint.messages_control]
max-line-length = 88
disable = [
    "missing-class-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
]
good-names = [
    "X",
    "y",
    "df",
    "ax",
    "a",
    "i",
    "C",
    "cv",
]


[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true


[tool.black]
line-length = 88
target-version = ['py310']


[tool.pytest.ini_options]
testpaths = [
    "src/tests",
]
